baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'DeepMap'
theme = 'digitalgarden'

googleAnalytics = "UA-PROPERTY_ID"

[Params]
  description = "My Digital Garden on the Internet"
  images = ['/digital-garden-logo.png']
  enableSearch = true

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Examples'
  url = '/examples'
  weight = 3


[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com'
  weight = 1
[[menu.social]]
  name = 'Email'
  url = '15158604383@163.com'
  weight = 2


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
